djangoProject/simpleproject/simpleproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('search',include('searchfeatures.urls')),
    path('stock/',include('stockmanager.urls')),
    #path('layout',include('warehouselayout.urls')),
]

djangoProject/simpleproject/stockmanager/urls.py
from django.urls import path,include
from . import views

app_name = 'stockmanager'

urlpatterns = [
    path("item_index/", views.ItemIndexView.as_view(), name="item_index"),
    path("item_index/<int:pk>", views.ItemView.as_view(), name='item'),
    path("location_index/", views.LocationIndexView.as_view(), name="location_index"),
    path("location_index/<int:pk>", views.LocationView.as_view(), name='location'),
]

djangoProject/simpleproject/stockmanager/models.py
from django.db import models
# Need to add save features

class Location(models.Model):

    f_num = models.CharField(max_length=2)
    m_num = models.CharField(max_length=1,default=0)
    l_num = models.CharField(max_length=1,default=0)
    
    class Meta:
        ordering = ["f_num","m_num","l_num"]

    def __str__(self):
        return "F.{} M.{} L.{}".format(self.f_num,self.m_num,self.l_num)
    
class Item(models.Model):
    item_name = models.CharField(max_length=200)
    article_number = models.CharField(max_length=6,default="0")
    locations = models.ManyToManyField(Location)

    class Meta:
        ordering = ["item_name"]

    def __str__(self):
        return self.item_name

djangoProject/simpleproject/warehouselayout/models.py
from django.db import models


# Create your models here.

djangoProject/simpleproject/searchfeatures/views.py
from django.shortcuts import render

# Create your views here.

djangoProject/simpleproject/stockmanager/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic
from stockmanager.models import Location,Item

class ItemView(generic.DetailView):
    model = Item
    template_name = "stockmanager/item.html"
    context_object_name = "item"
    

class ItemIndexView(generic.ListView):
    model = Item
    context_object_name = "item_set"
    template_name = "stockmanager/item_index.html"

    def get_queryset(self):
        return Item.objects.all()
    

class LocationView(generic.DetailView):
    model = Location
    template_name = "stockmanager/location.html"
    context_object_name = "location"

class LocationIndexView(generic.ListView):
    model = Location
    context_object_name = "location_set"
    template_name = "stockmanager/location_index.html"

    def get_queryset(self):
        return Location.objects.all()
    

djangoProject/simpleproject/warehouselayout/views.py
from django.shortcuts import render

# Create your views here.

djangoProject/simpleproject/stockmanager/templates/stockmanager/item.html
<h1>{{ item.item_name }}</h1>
<h2>{{ item.article_number }}</h2>
<ul>
{% for location in item.locations.all %}
    <li>F.{{ location.f_num }} M.{{ location.m_num }} L.{{ location.l_num }}</li>
{% endfor %}
</ul> 
<a href="{% url 'stockmanager:item_index' %}">Go Back?</a>

djangoProject/simpleproject/stockmanager/templates/stockmanager/item_index.html
<ul>
{% for item in item_set %}
<li><a href="{% url 'stockmanager:item' item.id %}">Name:   {{ item.item_name }}               Article: {{ item.article_number }}</a></li>
{% endfor %}
</ul>

djangoProject/simpleproject/stockmanager/templates/stockmanager/location.html
<h1>{{ location.f_num }}</h1>
<h2>{{ location.m_num }}</h2>
<h3>{{ location.l_num }}</h3>
<ul>
{% for item in location.item_set.all %}
    <li>Name : {{ item.item_name }}</li>
{% endfor %}
</ul>
<a href="{% url 'stockmanager:location_index' %}">Go Back?</a>

djangoProject/simpleproject/stockmanager/templates/stockmanager/location_index.html
<ul>
  {% for location in location_set %}
  <li><a href="{% url 'stockmanager:location' location.id %}">{{ location }}</a></li>
  {% endfor %}
</ul>

djangoProject/simpleproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

djangoProject/simpleproject/templates/mainpage.html
{% extends base.html %}

{% block content %}
<div id="warehouse_layout">

</div>
<div id="search">

</div>
{% endblock %}

djangoProject/simpleproject/warehouselayout/templates/warehouselayout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BASE</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>